CREATE TABLE IF NOT EXISTS restaurant_status (
  status_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS reservation_status (
  reservation_status_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS restaurant (
  restaurant_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  phone_number VARCHAR(30) NOT NULL,
  manager_restaurant_id BIGINT NULL,
  status_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS staff (
  staff_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS staff_member (
  staff_member_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(100) NOT NULL,
  salary DECIMAL(10,2) NOT NULL,
  employer_staff_id BIGINT NULL,
  restaurant_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (salary >= 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS staff_shift_log (
  shift_log_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  staff_id BIGINT NOT NULL,
  shift_time DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `tables` (
  table_number INT PRIMARY KEY,
  restaurant_id BIGINT NOT NULL,
  capacity INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (capacity > 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS floor_table (
  table_number INT PRIMARY KEY,
  capacity INT NOT NULL,
  location VARCHAR(100) NOT NULL,
  served_by_staff_member_id BIGINT NULL,
  CHECK (capacity > 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS reservation (
  reservation_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  table_number INT NOT NULL,
  reservation_time DATETIME NOT NULL,
  reservation_status_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS table_assignment (
  assignment_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  table_number INT NOT NULL,
  reservation_id BIGINT NULL,
  menu_price DECIMAL(10,2) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (menu_price IS NULL OR menu_price >= 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS menu_category (
  category_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  restaurant_id BIGINT NOT NULL,
  name VARCHAR(120) NOT NULL,
  current_location VARCHAR(120) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dish (
  item_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  restaurant_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  category_name VARCHAR(120) NOT NULL,
  item_name VARCHAR(150) NOT NULL,
  description TEXT NULL,
  is_alcoholic BOOLEAN NOT NULL DEFAULT FALSE,
  is_vegetarian BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS recipe (
  recipe_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  item_id BIGINT NOT NULL,
  is_alcoholic BOOLEAN NOT NULL DEFAULT FALSE,
  is_vegetarian BOOLEAN NOT NULL DEFAULT FALSE,
  instructions TEXT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS customer (
  customer_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(150) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS kitchen_ticket_log (
  kitchen_ticket_log_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer_id BIGINT NOT NULL,
  emergency_id VARCHAR(100) NULL,
  dispatch_time DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS customer_order (
  customer_order_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer_id BIGINT NOT NULL,
  table_number INT NOT NULL,
  dish_type VARCHAR(50) NOT NULL,
  time_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ticket (
  ticket_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer_order_id BIGINT NOT NULL,
  party_size INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (party_size > 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS order_ticket (
  order_ticket_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  ticket_id BIGINT NOT NULL,
  customer_order_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS emergency_request (
  order_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_ticket_id BIGINT NOT NULL,
  order_time DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS payment_area (
  payment_area_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  emergency_order_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS kitchen_order (
  kitchen_order_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  table_number INT NOT NULL,
  staff_member_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS service_order (
  service_order_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  table_number INT NOT NULL,
  is_alcoholic BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS supplier (
  supplier_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  company_name VARCHAR(150) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ingredient_stock (
  ingredient_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  stock_level DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (stock_level >= 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS supplier_ingredient_stock (
  supplier_id BIGINT NOT NULL,
  ingredient_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (supplier_id, ingredient_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS supplement_maintenance_log (
  maintenance_log_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  supplier_id BIGINT NOT NULL,
  company_name VARCHAR(150) NOT NULL,
  logged_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  details TEXT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS job_assignment (
  assignment_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  staff_id BIGINT NOT NULL,
  shift_time DATETIME NOT NULL,
  restaurant_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS equipment (
  equipment_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  assignment_id BIGINT NOT NULL,
  name VARCHAR(120) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
